### ISSUE TITLE
基本的な,echo の機能の開発

### ISSUE THREAD

**Issue by ntk221** [ntk221/mini_mini_shell#12]
- [x] #15

**Comment by molhot** [comment]
echo 12 13 なら　12 13が出るが
現状では
echo 12 13            12
となってしまう、解消する必要がある

**Comment by molhot** [comment]
echo |
となったとき本家なら入力待ちにならないといけない

**Comment by ntk221** [comment]
knitta は，一つ上の問題を先に対応するべきだと思いますた。
パイプについては，先の問題を解決してから，別のissue に立て直して開発してもいいかもしれません。

**Comment by ntk221** [comment]
- [ ]基本的な，echo 開発の続き
