### ISSUE TITLE
最弱のシェルのようなものを作りたい

### ISSUE THREAD

**Issue by ntk221** [ntk221/mini_mini_shell#6]
- [ ] #7

- [X] read で読み込んだ コマンド列を 分割する関数の実装 (satushi)

- [x] #12

**Comment by ntk221** [comment]
split_test において，test ケースを連続して split を呼び出した場合，二回目の呼び出しで，引数として渡した文字列の受け取りに失敗している。

**Comment by ntk221** [comment]
https://kymmo.hatenablog.com/entry/2021/02/01/150633

https://honobonolab.com/git-merge-conflict-delete/

**Comment by molhot** [comment]
- [ ] 明日やること
main関数でreadで読み込むときに100を指定してしまっている
結果として実行結果がおかしくなってしまっている
なので、100の箇所を修正したい

**Comment by ntk221** [comment]
前日の satushi の開発の結果を，knitta のローカルと同期に成功

**Comment by molhot** [comment]
- [ ] command_excecution内のファイル名をわかりやすい物に変更する

**Comment by molhot** [comment]
- [ ] obtaincommandinfoの因数で第三因数に何個のinput(空白で区切られたもの）があるか入れた方がいいかもしれないが現状不要

**Comment by ntk221** [comment]
echo ができるシェルができた！
